export const mockFigmaData = {
  id: '1307:713',
  name: 'Commercial icons',
  type: 'CANVAS',
  children: [
    {
      id: '1307:716',
      name: 'Q',
      type: 'FRAME',
      blendMode: 'PASS_THROUGH',
      children: [
        {
          id: '1307:714',
          name: 'Q',
          type: 'TEXT',
          blendMode: 'PASS_THROUGH',
          absoluteBoundingBox: { x: -297, y: -104, width: 54, height: 70 },
          constraints: { vertical: 'TOP', horizontal: 'LEFT' },
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: { r: 0.23529411852359772, g: 0.23529411852359772, b: 0.23529411852359772, a: 1 },
            },
          ],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'OUTSIDE',
          styles: { fill: '145:94' },
          effects: [],
          characters: 'Q',
          style: {
            fontFamily: 'Codec Pro',
            fontPostScriptName: 'CodecPro-UltraItalic',
            italic: true,
            fontWeight: 400,
            textCase: 'UPPER',
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 70,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 70,
            lineHeightPercent: 85.33333587646484,
            lineHeightPercentFontSize: 100,
            lineHeightUnit: 'FONT_SIZE_%',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
          lineTypes: ['NONE'],
          lineIndentations: [0],
        },
        {
          id: '1307:711',
          name: 'quote-left-solid',
          type: 'COMPONENT_SET',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: '1307:710',
              name: 'size=80',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:662',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:662;1098:448',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -195, y: -80, width: 80, height: 80 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 64,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 75,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -195, y: -80, width: 80, height: 80 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  fills: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '1098:449',
                },
              ],
              absoluteBoundingBox: { x: -195, y: -80, width: 80, height: 80 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:709',
              name: 'size=24',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:679',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:679;293:153',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -195, y: 24, width: 24, height: 24 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 19,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 22.265625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -195, y: 24, width: 24, height: 24 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:152',
                },
              ],
              absoluteBoundingBox: { x: -195, y: 24, width: 24, height: 24 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:708',
              name: 'size=16',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:685',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:685;293:141',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -195, y: 72, width: 16, height: 16 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 12,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 14.0625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -195, y: 72, width: 16, height: 16 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:145',
                },
              ],
              absoluteBoundingBox: { x: -195, y: 72, width: 16, height: 16 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
          ],
          absoluteBoundingBox: { x: -219, y: -104, width: 128, height: 216 },
          constraints: { vertical: 'TOP', horizontal: 'LEFT' },
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          clipsContent: true,
          background: [],
          fills: [],
          strokes: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: { r: 0.48235294222831726, g: 0.3803921639919281, b: 1, a: 1 },
            },
          ],
          cornerRadius: 5,
          rectangleCornerRadii: [0, 0, 0, 0],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
          layoutMode: 'VERTICAL',
          itemSpacing: 24,
          paddingLeft: 24,
          paddingRight: 24,
          paddingTop: 24,
          paddingBottom: 24,
          exportSettings: [
            { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
            { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
          ],
          effects: [],
        },
      ],
      absoluteBoundingBox: { x: -321, y: -128, width: 254, height: 264 },
      constraints: { vertical: 'TOP', horizontal: 'LEFT' },
      clipsContent: false,
      background: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 1 } }],
      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 1 } }],
      strokes: [],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      backgroundColor: { r: 1, g: 1, b: 1, a: 1 },
      styles: { fills: '145:96' },
      layoutMode: 'HORIZONTAL',
      itemSpacing: 24,
      paddingLeft: 24,
      paddingRight: 24,
      paddingTop: 24,
      paddingBottom: 24,
      effects: [],
    },
    {
      id: '1307:717',
      name: 'S',
      type: 'FRAME',
      blendMode: 'PASS_THROUGH',
      children: [
        {
          id: '1307:715',
          name: 'S',
          type: 'TEXT',
          blendMode: 'PASS_THROUGH',
          absoluteBoundingBox: { x: -297, y: 228, width: 45, height: 70 },
          constraints: { vertical: 'TOP', horizontal: 'LEFT' },
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          fills: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: { r: 0.23529411852359772, g: 0.23529411852359772, b: 0.23529411852359772, a: 1 },
            },
          ],
          strokes: [],
          strokeWeight: 1,
          strokeAlign: 'OUTSIDE',
          styles: { fill: '145:94' },
          effects: [],
          characters: 'S',
          style: {
            fontFamily: 'Codec Pro',
            fontPostScriptName: 'CodecPro-UltraItalic',
            italic: true,
            fontWeight: 400,
            textCase: 'UPPER',
            textAutoResize: 'WIDTH_AND_HEIGHT',
            fontSize: 70,
            textAlignHorizontal: 'LEFT',
            textAlignVertical: 'TOP',
            letterSpacing: 0,
            lineHeightPx: 70,
            lineHeightPercent: 85.33333587646484,
            lineHeightPercentFontSize: 100,
            lineHeightUnit: 'FONT_SIZE_%',
          },
          characterStyleOverrides: [],
          styleOverrideTable: {},
          lineTypes: ['NONE'],
          lineIndentations: [0],
        },
        {
          id: '1307:703',
          name: 'star-solid',
          type: 'COMPONENT_SET',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: '1307:702',
              name: 'size=80',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:654',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:654;1098:448',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -204, y: 252, width: 80, height: 80 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 64,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 75,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -204, y: 252, width: 80, height: 80 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  fills: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '1098:449',
                },
              ],
              absoluteBoundingBox: { x: -204, y: 252, width: 80, height: 80 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:701',
              name: 'size=24',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:677',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:677;293:153',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -204, y: 356, width: 24, height: 24 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 19,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 22.265625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -204, y: 356, width: 24, height: 24 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:152',
                },
              ],
              absoluteBoundingBox: { x: -204, y: 356, width: 24, height: 24 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:700',
              name: 'size=16',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:683',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:683;293:141',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -204, y: 404, width: 16, height: 16 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 12,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 14.0625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -204, y: 404, width: 16, height: 16 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:145',
                },
              ],
              absoluteBoundingBox: { x: -204, y: 404, width: 16, height: 16 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
          ],
          absoluteBoundingBox: { x: -228, y: 228, width: 128, height: 216 },
          constraints: { vertical: 'TOP', horizontal: 'LEFT' },
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          clipsContent: true,
          background: [],
          fills: [],
          strokes: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: { r: 0.48235294222831726, g: 0.3803921639919281, b: 1, a: 1 },
            },
          ],
          cornerRadius: 5,
          rectangleCornerRadii: [0, 0, 0, 0],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
          layoutMode: 'VERTICAL',
          itemSpacing: 24,
          paddingLeft: 24,
          paddingRight: 24,
          paddingTop: 24,
          paddingBottom: 24,
          exportSettings: [
            { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
            { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
          ],
          effects: [],
        },
        {
          id: '1307:707',
          name: 'star-half-solid',
          type: 'COMPONENT_SET',
          blendMode: 'PASS_THROUGH',
          children: [
            {
              id: '1307:706',
              name: 'size=80',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:658',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:658;1098:448',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -52, y: 252, width: 80, height: 80 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 64,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 75,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -52, y: 252, width: 80, height: 80 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  fills: [
                    {
                      blendMode: 'NORMAL',
                      visible: false,
                      type: 'SOLID',
                      color: { r: 1, g: 1, b: 1, a: 1 },
                    },
                  ],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '1098:449',
                },
              ],
              absoluteBoundingBox: { x: -52, y: 252, width: 80, height: 80 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:705',
              name: 'size=24',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:678',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:678;293:153',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -52, y: 356, width: 24, height: 24 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 19,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 22.265625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -52, y: 356, width: 24, height: 24 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:152',
                },
              ],
              absoluteBoundingBox: { x: -52, y: 356, width: 24, height: 24 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
            {
              id: '1307:704',
              name: 'size=16',
              type: 'COMPONENT',
              blendMode: 'PASS_THROUGH',
              children: [
                {
                  id: '1307:684',
                  name: '_IconPrimitive',
                  type: 'INSTANCE',
                  blendMode: 'PASS_THROUGH',
                  children: [
                    {
                      id: 'I1307:684;293:141',
                      name: 'Icon',
                      type: 'TEXT',
                      blendMode: 'PASS_THROUGH',
                      absoluteBoundingBox: { x: -52, y: 404, width: 16, height: 16 },
                      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 0, g: 0, b: 0, a: 1 } }],
                      strokes: [],
                      strokeWeight: 1,
                      strokeAlign: 'OUTSIDE',
                      styles: { fill: '145:95' },
                      effects: [],
                      characters: '',
                      style: {
                        fontFamily: 'Font Awesome 5 Pro',
                        fontPostScriptName: 'FontAwesome5Pro-Solid',
                        fontWeight: 400,
                        textCase: 'UPPER',
                        fontSize: 12,
                        textAlignHorizontal: 'CENTER',
                        textAlignVertical: 'CENTER',
                        letterSpacing: 0,
                        lineHeightPx: 14.0625,
                        lineHeightPercent: 100,
                        lineHeightUnit: 'INTRINSIC_%',
                      },
                      layoutVersion: 3,
                      characterStyleOverrides: [],
                      styleOverrideTable: {},
                      lineTypes: ['NONE'],
                      lineIndentations: [0],
                    },
                  ],
                  absoluteBoundingBox: { x: -52, y: 404, width: 16, height: 16 },
                  preserveRatio: true,
                  constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
                  clipsContent: false,
                  background: [],
                  fills: [],
                  strokes: [],
                  strokeWeight: 1,
                  strokeAlign: 'INSIDE',
                  backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
                  effects: [],
                  componentId: '293:145',
                },
              ],
              absoluteBoundingBox: { x: -52, y: 404, width: 16, height: 16 },
              constraints: { vertical: 'TOP', horizontal: 'LEFT' },
              layoutAlign: 'INHERIT',
              layoutGrow: 0,
              clipsContent: false,
              background: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              fills: [
                {
                  blendMode: 'NORMAL',
                  visible: false,
                  type: 'SOLID',
                  color: { r: 1, g: 1, b: 1, a: 1 },
                },
              ],
              strokes: [],
              strokeWeight: 1,
              strokeAlign: 'INSIDE',
              backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
              exportSettings: [
                { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
                { suffix: '', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
              ],
              effects: [],
            },
          ],
          absoluteBoundingBox: { x: -76, y: 228, width: 128, height: 216 },
          constraints: { vertical: 'TOP', horizontal: 'LEFT' },
          layoutAlign: 'INHERIT',
          layoutGrow: 0,
          clipsContent: true,
          background: [],
          fills: [],
          strokes: [
            {
              blendMode: 'NORMAL',
              type: 'SOLID',
              color: { r: 0.48235294222831726, g: 0.3803921639919281, b: 1, a: 1 },
            },
          ],
          cornerRadius: 5,
          rectangleCornerRadii: [0, 0, 0, 0],
          strokeWeight: 1,
          strokeAlign: 'INSIDE',
          backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
          layoutMode: 'VERTICAL',
          itemSpacing: 24,
          paddingLeft: 24,
          paddingRight: 24,
          paddingTop: 24,
          paddingBottom: 24,
          exportSettings: [
            { suffix: '', format: 'PNG', constraint: { type: 'SCALE', value: 1 } },
            { suffix: '@', format: 'SVG', constraint: { type: 'SCALE', value: 1 } },
          ],
          effects: [],
        },
      ],
      absoluteBoundingBox: { x: -321, y: 204, width: 397, height: 264 },
      constraints: { vertical: 'TOP', horizontal: 'LEFT' },
      clipsContent: false,
      background: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 1 } }],
      fills: [{ blendMode: 'NORMAL', type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 1 } }],
      strokes: [],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      backgroundColor: { r: 1, g: 1, b: 1, a: 1 },
      styles: { fills: '145:96' },
      layoutMode: 'HORIZONTAL',
      itemSpacing: 24,
      paddingLeft: 24,
      paddingRight: 24,
      paddingTop: 24,
      paddingBottom: 24,
      effects: [],
    },
  ],
  backgroundColor: { r: 0.9490196108818054, g: 0.9490196108818054, b: 0.9490196108818054, a: 1 },
  prototypeStartNodeID: null,
  flowStartingPoints: [],
  prototypeDevice: { type: 'NONE', rotation: 'NONE' },
};
