export const ERROR_CODES = {
  BAD_REQUEST: 400,
  NOT_AUTHORIZED: 403,
  PADE_NOT_FOUND: 404,
  LOCKED: 423,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  MAINTENANCE: 'maintenance',
} as const;
