type Surface =
  | '100'
  | '150'
  | '200'
  | '300'
  | 'Primary'
  | 'Secondary'
  | 'Error'
  | 'Info'
  | 'Neutral'
  | 'Success'
  | 'Warning';
type CurrentSurface = 'Current';
type AllSurface = Surface | CurrentSurface;

export type DefaultColor =
  | 'text/onSurfaceDefault/default'
  | 'text/onSurfaceDefault/active'
  | 'text/onSurfaceDefault/error'
  | 'text/onSurfaceDefault/secondary'
  | 'text/onSurfaceDefault/disabled'
  | 'text/onSurfaceDefault/placeholder'
  | 'text/onSurfaceDefault/primary/default'
  | 'text/onSurfaceDefault/primary/active'
  | 'border/onSurfaceDefault/disabled'
  | 'border/onSurfaceDefault/error'
  | 'border/onSurfaceDefault/selected'
  | 'border/onSurfaceDefault/focus'
  | 'border/onSurfaceDefault/action/tertiary'
  | 'border/onSurfaceDefault/default'
  | 'line/onSurfaceDefault/default'
  | 'line/onSurfaceDefault/primary'
  | 'icon/onSurfaceDefault/default'
  | 'icon/onSurfaceDefault/action/default'
  | 'accents/onSurfaceDefault/primary/default'
  | 'accents/onSurfaceDefault/primary/hover'
  | 'accents/onSurfaceDefault/primary/active';

export type InvertedColor =
  | 'text/onSurfaceInverted/default'
  | 'text/onSurfaceInverted/active'
  | 'text/onSurfaceInverted/error'
  | 'text/onSurfaceInverted/secondary'
  | 'text/onSurfaceInverted/disabled'
  | 'text/onSurfaceInverted/primary/default'
  | 'text/onSurfaceInverted/primary/active'
  | 'text/onSurfaceInverted/placeholder'
  | 'border/onSurfaceInverted/disabled'
  | 'border/onSurfaceInverted/error'
  | 'border/onSurfaceInverted/selected'
  | 'border/onSurfaceInverted/focus'
  | 'border/onSurfaceInverted/action/tertiary'
  | 'border/onSurfaceInverted/default'
  | 'line/onSurfaceInverted/default'
  | 'icon/onSurfaceInverted/default'
  | 'icon/onSurfaceInverted/action/default'
  | 'accents/onSurfaceInverted/primary/default'
  | 'accents/onSurfaceInverted/primary/hover'
  | 'accents/onSurfaceInverted/primary/active';

export type CurrentColor =
  | `bg/surface${CurrentSurface}/default`
  | `bg/surface${CurrentSurface}/hover`
  | `bg/surface${CurrentSurface}/active`;

export type ExtraColor =
  | `text/onSurface${AllSurface}/error`
  | `text/onSurface${AllSurface}/active`
  | `text/onSurface${AllSurface}/default`
  | `text/onSurface${AllSurface}/disabled`
  | `text/onSurface${AllSurface}/secondary`
  | `text/onSurface${AllSurface}/placeholder`
  | `text/onSurface${AllSurface}/primary/default`
  | `text/onSurface${AllSurface}/primary/active`
  | `border/onSurface${AllSurface}/error`
  | `border/onSurface${AllSurface}/focus`
  | `border/onSurface${AllSurface}/default`
  | `border/onSurface${AllSurface}/disabled`
  | `border/onSurface${AllSurface}/selected`
  | `border/onSurface${AllSurface}/action/tertiary`
  | `line/onSurface${AllSurface}/default`
  | `icon/onSurface${AllSurface}/default`
  | `icon/onSurface${AllSurface}/inverted`
  | `icon/onSurface${AllSurface}/action/default`
  | `accents/onSurface${AllSurface}/primary/default`
  | `accents/onSurface${AllSurface}/primary/hover`
  | `accents/onSurface${AllSurface}/primary/active`;

export type Color =
  | 'bg/backdrop/dark'
  | 'bg/backdrop/light'
  | 'bg/disabled'
  | 'bg/commercial/new1'
  | 'bg/commercial/new2'
  | 'bg/commercial/promo1'
  | 'bg/commercial/promo2'
  | 'bg/commercial/reconditioned1'
  | 'bg/commercial/reconditioned2'
  | 'bg/commercial/warranty1'
  | 'bg/commercial/warranty2'
  | 'bg/error/input'
  | 'bg/iconButton/list/default'
  | 'bg/iconButton/list/hover'
  | 'bg/iconButton/list/checked'
  | 'bg/iconButton/list/active'
  | 'bg/surface100/default'
  | 'bg/surface100/active'
  | 'bg/surface100/hover'
  | 'bg/surface200/default'
  | 'bg/surface200/hover'
  | 'bg/surface200/active'
  | 'bg/surface300/default'
  | 'bg/surface300/hover'
  | 'bg/surface300/active'
  | 'bg/surface400/default'
  | 'bg/surface400/hover'
  | 'bg/surface400/active'
  | 'bg/table/selected'
  | 'bg/surface150/default'
  | 'bg/surface150/hover'
  | 'bg/surface150/active'
  | 'bg/surfacePrimary/default'
  | 'bg/surfacePrimary/hover'
  | 'bg/surfacePrimary/active'
  | 'bg/surfaceSecondary/default'
  | 'bg/surfaceSecondary/hover'
  | 'bg/surfaceSecondary/active'
  | 'bg/surfaceInverted/hover'
  | 'bg/surfaceInverted/active'
  | 'bg/surfaceTransparent/hover'
  | 'bg/surfaceTransparent/active'
  | 'bg/surfaceError/default'
  | 'bg/surfaceError/hover'
  | 'bg/surfaceError/active'
  | 'bg/surfaceInfo/default'
  | 'bg/surfaceInfo/hover'
  | 'bg/surfaceInfo/active'
  | 'bg/surfaceNeutral/default'
  | 'bg/surfaceNeutral/hover'
  | 'bg/surfaceNeutral/active'
  | 'bg/surfaceSuccess/default'
  | 'bg/surfaceSuccess/hover'
  | 'bg/surfaceSuccess/active'
  | 'bg/surfaceWarning/default'
  | 'bg/surfaceWarning/hover'
  | 'bg/surfaceWarning/active'
  | 'bg/transparent/onSurfaceSecondary/hover'
  | 'bg/transparent/onSurfaceSecondary/active'
  | 'border/onFlag'
  | 'icon/success'
  | 'icon/warning'
  | 'icon/error'
  | 'icon/info'
  | 'icon/onIconButton/list/default'
  | 'nav/scrollbar'
  | 'text/onFeedback'
  | 'text/promo'
  | 'text/onCommercial/new'
  | 'text/onCommercial/promo'
  | 'text/onCommercial/reconditioned1'
  | 'text/onCommercial/reconditioned2'
  | 'text/onCommercial/warranty1'
  | 'text/onCommercial/warranty2';
